### ISSUE TITLE
Create video script using a Superconductive example repo

### ISSUE THREAD

**Issue by Aylr** [great-expectations/great_expectations_action#70]
# Rough story outline focusing on code change story that does something incorrect and we fix it.

1. Create a SQL change
2. Submit PR
3. Action runs
4. CI fails
5. look at linked data docs
6. Ooops! I did a cross join (or other realistic SQL error)
7. Fix PR
8. CI runs and succeeds!
9. Profit

## TODO

- [ ] @Aylr finish setting up Action in demo repo
- [ ] @Aylr / @spbail to run through script
- [ ] Practice PR on demo repo
- [x] @Aylr to record video
